<?php
 $title = 'Acceso a Datos';
 $this->headTitle($title);
 var_dump($datos);
  ?>

<div class="row">

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    <a href="<?php echo $this->url('datos', array('action'=>'add'));?>">Agregar datos</a>
                </h3>
            </div>
            <div class="panel-body">
                <table class="table table-bordered table-striped">
                     <tr>
						<th>Nombre</th>
						<th>Foto</th>
						<th>Edad</th>
						<th>Fecha</th>
						<th>&nbsp;</th>
					</tr>
					<?php foreach($datos as $datosx) : ?>
					<tr>
						<td><?php echo $this->escapeHtml($datosx->nombre);?></td>
						<td><?php echo $this->escapeHtml($datosx->foto);?></td>
						<td><?php echo $this->escapeHtml($datosx->edad);?></td>
						<td><?php echo $this->escapeHtml($datosx->fecha);?></td>
						<td>
							<a href="<?php echo $this->url('datos',
								array('action'=>'edit', 'id' => $datosx->id));?>">Edit</a>
							<a href="<?php echo $this->url('datos',
								array('action'=>'delete', 'id' => $datosx->id));?>">Delete</a>
						</td>
					</tr>
					<?php endforeach; ?>
                </table>
            </div>
        </div>
    </div>

    
</div>



