<?php
$title = 'Eliminar album';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div class="row">

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
					Eliminar datos
                </h3>
            </div>
            <div class="panel-body">
	<p>Estas seguro que desea eliminar el album
	  '<?php echo $this->escapeHtml($album->title); ?>' por
	  '<?php echo $this->escapeHtml($album->artist); ?>'?
	</p>
	<?php 
	$url = $this->url('album', array('action' => 'delete', 'id'=>$this->id)); ?>
	<form action="<?php echo $url; ?>" method="post">
	<div>
	  <input type="hidden" name="id" value="<?php echo (int)$album->id; ?>" />
	  <input type="submit" name="del" value="Si" />
	  <input type="submit" name="del" value="No" />
	</div>
	</form>
			</div>
		</div>
	</div>
</div>