<div class="row">

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
					Mis Datos
                </h3>
            </div>
            <div class="panel-body">
				Enrique, esta es una de las características de las cosas que puedo hacer, no están desarrolladas desde cero pero han sido adaptadas al español, configuradas e instaladas para su correcto funcionamiento.
			</div>
		</div>
	</div>
</div>